sudo: required
language: java
jdk:
- oraclejdk8
before_script:
- sudo apt-get -qq update
- sudo apt-get install ant-optional -y
- sudo add-apt-repository ppa:eyecreate/logtalk -y
- sudo apt-get update
- sudo apt-get install logtalk -y
- mkdir ~/haxelib
- haxelib setup ~/haxelib
- haxelib install hxjava
- haxelib git debugger https://github.com/TiVo/debugger.git
- mkdir build
- mkdir report
script: make ANT_TARGET=$ANT_TARGET test
env:
    - IDEA_VERSION=2016.3.8 ANT_TARGET=test
    - IDEA_VERSION=2017.2.7 ANT_TARGET=test
    - IDEA_VERSION=2017.3.5 ANT_TARGET=test
    - IDEA_VERSION=2018.1 ANT_TARGET=test

notifications:
  email: false

jobs:
  include:
    - if: branch = develop
      script: make
      env:
        - IDEA_VERSION=2018.1 PLUGIN_VERSION=18
      after_success:
        - curl -k -i -F username="$PLUGIN_USER_NAME" -F password="$PLUGIN_USER_PASS" -F channel="EAP" -F pluginid=6873 -F file=intellij-logtalk-$PLUGIN_VERSION.jar https://plugins.jetbrains.com/plugin/uploadPlugin
